spring:
  profiles:
    acitve: ${SPRING_PROFILES_ACTIVE}
  rabbitmq:
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    queues:
      baseball-player: players-stats
    exchanges:
      baseball: baseball-stats
    bindings:
      baseball-player-stats: baseball-player-stats