spring:
  profiles:
    acitve: ${SPRING_PROFILES_ACTIVE}
  rabbitmq:
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    queues:
      baseball-player: players-stats
    exchanges:
      baseball: baseball-stats
    bindings:
      baseball-player-stats: baseball-player-stats
  datasoruce:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATSOURCE_URL}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
server:
  port: 8081